[build]
target = "src/arch/x86/x86-unknown-kernel.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-x86 -serial stdio -gdb tcp::1234 -no-shutdown -no-reboot -kernel"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
